### Register
POST http://localhost:4000/users
Content-Type: application/json

{
  "userName": "{{userName}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login
POST http://localhost:4000/users/session
Content-Type: application/json

{
  "userName": "{{userName}}",
  "password": "{{password}}"
}